# Generated by Django 2.2.28 on 2025-12-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0023_auto_20251113_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bestAnswer',
            field=models.ForeignKey(blank=True, help_text='被选为最佳答案的评论', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_answer_posts', to='baweb.PostComment', verbose_name='最佳答案'),
        ),
        migrations.AddField(
            model_name='post',
            name='bountyPoints',
            field=models.IntegerField(default=0, help_text='帖子悬赏的积分数量', verbose_name='悬赏积分'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='isBestAnswer',
            field=models.BooleanField(default=False, help_text='是否被选为该帖子的最佳答案', verbose_name='是否是最佳答案'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=100, help_text='用户积分，初始100分', verbose_name='积分'),
        ),
    ]
