# Generated by Django 3.2.25 on 2025-12-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0025_make_post_course_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-isPinned', '-heatScore', '-createdAt']},
        ),
        migrations.AddField(
            model_name='post',
            name='isPinned',
            field=models.BooleanField(default=False, help_text='教师可以置顶课程内的帖子', verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='post',
            name='pinnedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶时间'),
        ),
    ]
