# Generated by Django 3.2.25 on 2025-12-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0026_add_post_teacher_features'),
        ('baweb', '0026_auto_20251221_1517'),
    ]

    operations = [
    ]
