# Generated by Django 5.2.8 on 2025-12-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baweb", "0027_merge_20251221_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interactionHistory",
            field=models.TextField(
                blank=True,
                help_text="JSON格式的帖子交互历史 {postId: score}",
                verbose_name="交互历史",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferredCategories",
            field=models.TextField(
                blank=True,
                help_text="JSON格式的分类偏好 {categoryId: score}",
                verbose_name="偏好分类",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="userVector",
            field=models.BinaryField(
                blank=True,
                help_text="768维用户偏好向量，用于个性化推荐",
                null=True,
                verbose_name="用户向量",
            ),
        ),
        migrations.AlterField(
            model_name="contentcategory",
            name="name",
            field=models.SmallIntegerField(
                choices=[
                    (1, "问答"),
                    (2, "知识分享"),
                    (3, "资源分享"),
                    (4, "作业讨论"),
                    (5, "课程反馈"),
                    (6, "学习心得"),
                    (7, "求助"),
                    (8, "闲聊"),
                    (9, "通知公告"),
                    (10, "项目协作"),
                ],
                default=1,
                verbose_name="内容分类",
            ),
        ),
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewedAt",
                    models.DateTimeField(auto_now=True, verbose_name="浏览时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="baweb.post",
                        verbose_name="帖子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewed_posts",
                        to="baweb.user",
                        verbose_name="浏览用户",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "帖子浏览记录",
                "indexes": [
                    models.Index(
                        fields=["user", "-viewedAt"],
                        name="baweb_postv_user_id_ec40ca_idx",
                    ),
                    models.Index(
                        fields=["post"], name="baweb_postv_post_id_c57b0a_idx"
                    ),
                ],
                "unique_together": {("post", "user")},
            },
        ),
    ]
