# Generated by Django 5.2.8 on 2025-12-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baweb", "0028_user_interactionhistory_user_preferredcategories_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalizedPostScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personalizedScore",
                    models.FloatField(
                        default=0.0,
                        help_text="基于用户画像的个性化相关度分数（0-1）",
                        verbose_name="个性化分数",
                    ),
                ),
                (
                    "heatScore",
                    models.FloatField(
                        default=0.0,
                        help_text="帖子的基础热度分数",
                        verbose_name="热度分数",
                    ),
                ),
                (
                    "finalScore",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="个性化分数与热度分数的加权综合",
                        verbose_name="最终综合分数",
                    ),
                ),
                (
                    "calculatedAt",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="分数最后计算/更新的时间",
                        verbose_name="计算时间",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="用于追踪算法版本", verbose_name="版本号"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_scores",
                        to="baweb.post",
                        verbose_name="帖子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalized_scores",
                        to="baweb.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "个性化帖子分数缓存",
                "indexes": [
                    models.Index(
                        fields=["user", "-finalScore"],
                        name="baweb_perso_user_id_af6151_idx",
                    ),
                    models.Index(
                        fields=["post"], name="baweb_perso_post_id_d892f2_idx"
                    ),
                    models.Index(
                        fields=["-calculatedAt"], name="baweb_perso_calcula_ce02f6_idx"
                    ),
                ],
                "unique_together": {("user", "post")},
            },
        ),
    ]
